version: '3.8'

services:
  # Database
  postgres-dev:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: medianest_dev
      POSTGRES_USER: medianest
      POSTGRES_PASSWORD: medianest
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medianest"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Cache
  redis-dev:
    image: redis:7-alpine
    volumes:
      - redis_dev_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Development services can be added here
  # mailhog for email testing
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI

volumes:
  postgres_dev_data:
  redis_dev_data: