version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./backend/config:/app/config
      - backend_cache:/app/.cache
    environment:
      - FLASK_ENV=${FLASK_ENV:-development}
      - FLASK_DEBUG=${FLASK_DEBUG:-1}
      - FLASK_APP=${FLASK_APP:-app.py}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///dev.db}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - UPTIME_KUMA_URL=${UPTIME_KUMA_URL}
      - UPTIME_KUMA_API_KEY=${UPTIME_KUMA_API_KEY}
      - OVERSEERR_URL=${OVERSEERR_URL}
      - OVERSEERR_API_KEY=${OVERSEERR_API_KEY}
      - NFS_MOUNT_PATH=${NFS_MOUNT_PATH:-/mnt/media}
      - PYTHONPATH=/app
    networks:
      - medianest-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://backend:5000/api}
      - NODE_ENV=${NODE_ENV:-development}
    depends_on:
      - backend
    networks:
      - medianest-network

networks:
  medianest-network:
    driver: bridge

volumes:
  backend_cache:
  frontend_node_modules:

