version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.optimized
      target: production
      cache_from:
        - node:18-alpine
        - medianest-backend:cache
    image: medianest-backend:latest
    container_name: medianest-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=512
    networks:
      - medianest-network
    volumes:
      - backend-data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.optimized
      target: production
      cache_from:
        - node:18-alpine
        - medianest-frontend:cache
    image: medianest-frontend:latest
    container_name: medianest-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=256
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - medianest-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'

  nginx:
    image: nginx:alpine
    container_name: medianest-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infrastructure/nginx/compression.conf:/etc/nginx/conf.d/compression.conf:ro
    networks:
      - medianest-network
    depends_on:
      - backend
      - frontend
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.25'

volumes:
  backend-data:
    driver: local

networks:
  medianest-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
