services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medianest-app
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER:-medianest}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-medianest}?connection_limit=20&pool_timeout=30
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER:-medianest}
      - JWT_AUDIENCE=${JWT_AUDIENCE:-medianest-users}
      - PLEX_CLIENT_ID=${PLEX_CLIENT_ID}
      - PLEX_CLIENT_SECRET=${PLEX_CLIENT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
    volumes:
      - ./youtube:/app/youtube:rw
      - uploads:/app/uploads:rw
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    user: "1000:1000"
    networks:
      - medianest-network

  postgres:
    image: postgres:15-alpine
    container_name: medianest-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-medianest}
      - POSTGRES_USER=${POSTGRES_USER:-medianest}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/database/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    # ports:
      # - "5432:5432"  # Removed for security - use internal networking only
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-medianest}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - medianest-network

  redis:
    image: redis:7-alpine
    container_name: medianest-redis
    restart: unless-stopped
    command: >
      redis-server
      --appendonly yes
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    # ports:
      # - "6379:6379"  # Removed for security - use internal networking only
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - medianest-network

volumes:
  postgres_data:
  redis_data:
  uploads:

networks:
  medianest-network:
    driver: bridge