# MkDocs Configuration for MediaNest - Professional Documentation Platform
site_name: MediaNest Documentation
site_url: https://kinginyellow.github.io/medianest/  # GitHub Pages URL
site_author: MediaNest Development Team
site_description: Complete documentation for MediaNest - Advanced Media Management Platform with Plex Integration, API, and Developer Resources

# Repository Configuration
repo_name: kinginyellow/medianest
repo_url: https://github.com/kinginyellow/medianest
edit_uri: edit/develop/docs/
remote_branch: develop
remote_name: origin

# Copyright and Legal
copyright: >
  Copyright &copy; 2024 MediaNest Development Team -
  <a href="#__consent">Manage Cookies</a> |
  <a href="/privacy">Privacy Policy</a> |
  <a href="/terms">Terms of Service</a>

# Theme Configuration
theme:
  name: material
  custom_dir: docs/overrides

  # Color Scheme
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # Enhanced Features for Professional Documentation
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

  # Branding Assets
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico

  # Language
  language: en

  # Font
  font:
    text: Roboto
    code: Roboto Mono

# Navigation
nav:
  - Home: index.md

  - Getting Started:
      - getting-started/index.md
      - Quick Start: getting-started/quickstart.md
      - System Requirements: getting-started/requirements.md
      - First Time Setup: getting-started/first-setup.md

  - Installation:
      - installation/index.md
      - Docker Installation: installation/docker.md
      - Manual Installation: installation/manual.md
      - Configuration: installation/configuration.md
      - Environment Variables: installation/environment.md
      - Database Setup: installation/database.md

  - User Guides:
      - user-guides/index.md
      - Media Management: user-guides/media-management.md
      - File Organization: user-guides/file-organization.md
      - Search and Filtering: user-guides/search-filtering.md
      - Metadata Management: user-guides/metadata.md
      - Collections: user-guides/collections.md
      - Sharing and Permissions: user-guides/sharing.md
      - Backup and Sync: user-guides/backup-sync.md

  - API Reference:
      - api/index.md
      - Authentication: api/authentication.md
      - Media API: api/media.md
      - Collections API: api/collections.md
      - User Management: api/users.md
      - Search API: api/search.md
      - Webhooks: api/webhooks.md
      - Rate Limiting: api/rate-limiting.md
      - Error Handling: api/errors.md

  - Developer Docs:
      - developers/index.md
      - Architecture Overview: developers/architecture.md
      - Contributing: developers/contributing.md
      - Development Setup: developers/development-setup.md
      - Coding Standards: developers/coding-standards.md
      - Testing: developers/testing.md
      - Deployment: developers/deployment.md
      - Database Schema: developers/database-schema.md
      - Plugin Development: developers/plugins.md

  - Troubleshooting:
      - troubleshooting/index.md
      - Common Issues: troubleshooting/common-issues.md
      - Performance Issues: troubleshooting/performance.md
      - Database Issues: troubleshooting/database.md
      - Media Processing: troubleshooting/media-processing.md
      - Authentication Problems: troubleshooting/authentication.md
      - Logs and Debugging: troubleshooting/debugging.md

  - Reference:
      - reference/index.md
      - CLI Commands: reference/cli.md
      - Configuration Reference: reference/config-reference.md
      - Supported Formats: reference/formats.md
      - FAQ: reference/faq.md
      - Glossary: reference/glossary.md
      - Changelog: reference/changelog.md

# Enhanced Plugins for Professional Documentation
plugins:
  # Core search with advanced features
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang:
        - en
      # prebuild_index: true  # Not supported in this version

  # Performance optimization
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
        remove_empty_space: true

  # Git integration for content management
  - git-revision-date-localized:
      type: timeago
      timezone: UTC
      locale: en
      fallback_to_build_date: true
      enable_creation_date: true

  # Content organization
  - tags:

  # Social media integration
  - social:
      enabled: !ENV [CI, false]
      cards: true
      cards_layout_options:
        background_color: '#673ab7'
        color: '#ffffff'
      # cards_color deprecated - using cards_layout_options instead

  # Meta tags for SEO
  - meta

  # Privacy plugin for GDPR compliance
  - privacy:
      enabled: !ENV [CI, false]

# Markdown Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: medianest
      repo: medianest
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Enhanced Assets and Scripts
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/medianest-theme.css
  - assets/stylesheets/animations.css
  - assets/stylesheets/responsive.css

extra_javascript:
  - assets/javascripts/medianest.js
  - assets/javascripts/search-enhancements.js
  - assets/javascripts/analytics.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js

# Extended Configuration & Integrations
extra:
  # Version management with Mike
  version:
    provider: mike
    default: latest
    alias: true

  # Enhanced social links
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/medianest/medianest
      name: GitHub Repository
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/medianest/medianest
      name: Docker Hub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/medianest
      name: Discord Community
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/medianest
      name: Twitter Updates
    - icon: fontawesome/solid/globe
      link: https://medianest.com
      name: Official Website

  # Analytics and feedback
  analytics:
    provider: google
    property: !ENV [GOOGLE_ANALYTICS_KEY, '']
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback! Consider starring us on 
            <a href="https://github.com/medianest/medianest" target="_blank" rel="noopener">GitHub</a>
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve by
            <a href="https://github.com/medianest/medianest/issues/new/?title=[Docs]+{title}+-+{url}" target="_blank" rel="noopener">creating an issue</a>
            or <a href="https://github.com/medianest/medianest/edit/develop/docs/{path}" target="_blank" rel="noopener">editing this page</a>.

  # Status and announcements
  status:
    new: Recently added
    deprecated: Deprecated

  # Consent management for privacy
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
      - manage

  # Generator notice
  generator: false

# Validation
validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: ignore
    absolute_links: ignore
    unrecognized_links: ignore

# Watch
watch:
  - docs/
  - mkdocs.yml
