# MkDocs Configuration for MediaNest - Professional Documentation Platform
site_name: MediaNest Documentation
site_url: https://kinginyellow.github.io/medianest/  # GitHub Pages URL
site_author: MediaNest Development Team
site_description: Complete documentation for MediaNest - Advanced Media Management Platform with Plex Integration, API, and Developer Resources

# Repository Configuration
repo_name: kinginyellow/medianest
repo_url: https://github.com/kinginyellow/medianest
edit_uri: edit/develop/docs/
remote_branch: develop
remote_name: origin

# Copyright and Legal
copyright: >
  Copyright &copy; 2024 MediaNest Development Team -
  <a href="#__consent">Manage Cookies</a> |
  <a href="/privacy">Privacy Policy</a> |
  <a href="/terms">Terms of Service</a>

# Theme Configuration
theme:
  name: material

  # Color Scheme
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # Enhanced Features for Professional Documentation
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

  # Branding Assets
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico

  # Language
  language: en

  # Font
  font:
    text: Roboto
    code: Roboto Mono

# Navigation
nav:
  - Home: index.md
  - Getting Started:
      - getting-started/index.md
      - Quick Start: getting-started/quickstart.md
      - Development Setup: getting-started/development-setup.md
  - Architecture:
      - Component Architecture: architecture/component-architecture.md
      - Data Flow: architecture/data-flow.md
      - System Overview: architecture/system-overview.md
      - Architecture Decisions:
        - ADR-001 Architecture: architecture/decisions/adr-001-architecture.md
  - API Reference:
      - Overview: api/overview.md
      - WebSocket API: api/websocket.md
      - Endpoints:
        - Dashboard: api/endpoints/dashboard.md
        - Media: api/endpoints/media.md
        - Plex: api/endpoints/plex.md
  - Deployment:
      - CI/CD: deployment/ci-cd.md
  - Developers:
      - Contributing: developers/contributing.md
      - Workflow: developers/workflow.md
  - Visuals:
      - Database Schema: visuals/database-schema.md
      - Deployment Architecture: visuals/deployment-architecture.md
      - System Flow: visuals/system-flow.md
  - Standards:
      - Documentation Checklist: standards/documentation-checklist.md

# Essential Plugins - Minimal Working Configuration
plugins:
  # Core search functionality
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang:
        - en

  # Performance optimization
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
        remove_empty_space: true
        remove_optional_attribute_quotes: false
        reduce_empty_attributes: true

  # Git integration for content management
  - git-revision-date-localized:
      type: timeago
      timezone: UTC
      locale: en
      fallback_to_build_date: true
      enable_creation_date: true
      enable_git_follow: false

# Markdown Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      title: On this page
      baselevel: 1
      separator: "-"
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: kinginyellow
      repo: medianest
      normalize_issue_symbols: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
      base_path: 
        - docs/snippets
        - .
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: swagger-ui
          class: swagger-ui
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde

# Enhanced Assets and Scripts
extra_css:
  - stylesheets/extra.css
  - stylesheets/medianest-theme.css
  - stylesheets/animations.css
  - stylesheets/responsive.css
  - stylesheets/diagram-styles.css
  - stylesheets/api-docs.css
  - stylesheets/code-highlights.css
  - stylesheets/mermaid-custom.css

extra_javascript:
  - javascripts/extra.js
  - javascripts/medianest.js
  - javascripts/search-enhancements.js
  - javascripts/analytics.js
  - javascripts/api-explorer.js
  - javascripts/diagram-interactions.js
  - javascripts/mermaid-config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - https://unpkg.com/swagger-ui-dist@4.15.5/swagger-ui-bundle.js

# Extended Configuration & Integrations
extra:
  # Version management with Mike
  version:
    provider: mike
    default: latest
    alias: true

  # Enhanced social links
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/medianest/medianest
      name: GitHub Repository
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/medianest/medianest
      name: Docker Hub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/medianest
      name: Discord Community
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/medianest
      name: Twitter Updates
    - icon: fontawesome/solid/globe
      link: https://medianest.com
      name: Official Website

  # Analytics and feedback
  analytics:
    provider: google
    property: !ENV [GOOGLE_ANALYTICS_KEY, '']
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback! Consider starring us on 
            <a href="https://github.com/medianest/medianest" target="_blank" rel="noopener">GitHub</a>
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve by
            <a href="https://github.com/medianest/medianest/issues/new/?title=[Docs]+{title}+-+{url}" target="_blank" rel="noopener">creating an issue</a>
            or <a href="https://github.com/medianest/medianest/edit/develop/docs/{path}" target="_blank" rel="noopener">editing this page</a>.

  # Status and announcements
  status:
    new: Recently added
    deprecated: Deprecated

  # Consent management for privacy
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
      - manage

  # Generator notice
  generator: false

# Validation
validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: ignore
    absolute_links: ignore
    unrecognized_links: ignore

# Watch
watch:
  - docs/
  - mkdocs.yml
