# Grafana Datasources Configuration for MEDIANEST PLG Stack

apiVersion: 1

datasources:
  # Prometheus - Primary Metrics Datasource
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 5s
      manageAlerts: true
      alertmanagerUid: alertmanager
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: jaeger
    uid: prometheus-uid

  # Loki - Primary Logs Datasource  
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    version: 1
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - matcherRegex: 'correlationId=(\w+)'
          name: TraceID
          url: '$${__value.raw}'
          datasourceUid: jaeger
    uid: loki-uid

  # AlertManager - Alerting Datasource
  - name: AlertManager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    version: 1
    editable: true
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: false
    uid: alertmanager

  # PostgreSQL - Direct Database Queries (Optional)
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: medianest
    user: medianest
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    version: 1
    editable: true
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 15
      timescaledb: false
    uid: postgres-uid

  # Redis - Cache Metrics (via Redis Datasource Plugin)
  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis:6379
    version: 1
    editable: true
    jsonData:
      client: standalone
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
    secureJsonData:
      password: ${REDIS_PASSWORD}
    uid: redis-uid

  # Node Exporter Metrics (via Prometheus)
  - name: Node Exporter
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: jaeger
      # Pre-filter to only node-exporter metrics
      customQueryParameters: 'match[]={job="node-exporter"}'
    uid: node-exporter-uid

  # cAdvisor Metrics (via Prometheus)
  - name: cAdvisor
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      # Pre-filter to only container metrics
      customQueryParameters: 'match[]={job="cadvisor"}'
    uid: cadvisor-uid

  # TestData - For dashboard testing
  - name: TestData
    type: testdata
    access: proxy
    version: 1
    editable: true
    uid: testdata-uid