/**
 * Optimized Global Test Setup
 * Generated by Claude-Flow Performance Optimization Swarm
 */

export async function setup() {
  console.log('🚀 Initializing optimized test infrastructure...');
  
  // Global test state initialization
  globalThis.__TEST_INFRASTRUCTURE__ = {
    dbPool: null,
    redisClient: null,
    testData: new Map(),
    startTime: Date.now()
  };

  console.log('✅ Test infrastructure initialized successfully');
}

export async function teardown() {
  console.log('🧹 Cleaning up test infrastructure...');
  
  // Cleanup global resources
  if (globalThis.__TEST_INFRASTRUCTURE__) {
    const { dbPool, redisClient } = globalThis.__TEST_INFRASTRUCTURE__;
    
    if (dbPool?.destroy) {
      await dbPool.destroy();
    }
    
    if (redisClient?.disconnect) {
      await redisClient.disconnect();
    }
    
    globalThis.__TEST_INFRASTRUCTURE__ = null;
  }
  
  console.log('✅ Test infrastructure cleanup completed');
}