blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/KingInYellow18/medianets-github/discussions
    about: Please use GitHub Discussions for questions and general discussions
  - name: Security Issues
    url: https://github.com/KingInYellow18/medianets-github/security/advisories/new
    about: Please report security vulnerabilities through GitHub Security Advisories