name: 4-Tier Branch Merge Flow

on:
  push:
    branches: [ claude-flow, test, development ]
  pull_request:
    branches: [ main, development, test ]

jobs:
  validate-merge-flow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Validate Branch Hierarchy
        run: |
          echo "=== 4-Tier Branch Structure Validation ==="
          echo "Structure: main ← development ← test ← claude-flow"
          
          # Check if all required branches exist
          git branch -r | grep -E "(main|development|test|claude-flow)" || {
            echo "❌ Required branches missing"
            exit 1
          }
          
          echo "✅ All required branches present"
          
      - name: Validate Merge Direction
        run: |
          CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
          echo "Current branch: $CURRENT_BRANCH"
          
          case $CURRENT_BRANCH in
            claude-flow)
              echo "✅ Claude-flow branch - experimental work allowed"
              ;;
            test)
              echo "✅ Test branch - testing and validation"
              ;;
            development)
              echo "✅ Development branch - stable development"
              ;;
            main)
              echo "✅ Main branch - production ready"
              ;;
            *)
              echo "⚠️ Non-standard branch: $CURRENT_BRANCH"
              ;;
          esac

  test-on-merge:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            frontend/package-lock.json
            backend/package-lock.json
      
      - name: Install Dependencies
        run: |
          npm ci
          if [ -d "frontend" ]; then cd frontend && npm ci && cd ..; fi
          if [ -d "backend" ]; then cd backend && npm ci && cd ..; fi
      
      - name: Run Tests
        run: |
          npm test
          if [ -d "frontend" ]; then cd frontend && npm test && cd ..; fi
          if [ -d "backend" ]; then cd backend && npm test && cd ..; fi

  deployment-readiness:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [validate-merge-flow, test-on-merge]
    steps:
      - uses: actions/checkout@v4
      
      - name: Production Readiness Check
        run: |
          echo "=== Production Readiness Validation ==="
          echo "✅ Code merged to main branch"
          echo "✅ All tests passed"
          echo "✅ Branch hierarchy validated"
          echo "🚀 Ready for deployment"