name: CI

on:
  push:
    branches: [main, develop, staging]
  pull_request:
    branches: [main, staging]

env:
  NODE_VERSION: '20'

jobs:
  # Simplified CI for active development - Basic lint check only
  lint:
    name: Quick Lint Check
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run basic linter (continue on error)
        run: npm run lint || echo "Lint warnings found but continuing..."
        continue-on-error: true

  # Basic security scan (optional for development)
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run basic security scan (continue on error)
        run: echo "Security scan placeholder - implement as needed"
        continue-on-error: true
