name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # Check PR title follows conventional commits
  pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert

  # Check file sizes
  file-size:
    name: Check File Sizes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check for large files
        run: |
          find . -type f -size +1M | grep -v node_modules | grep -v .git > large_files.txt || true
          if [ -s large_files.txt ]; then
            echo "Large files detected:"
            cat large_files.txt
            exit 1
          fi